const express=require('express');
const router=express.Router();
const homeController=require('../controllers/home_controller');
router.get('/',homeController.homeSignUp);
router.get('/signIn', homeController.signIn);
router.use('/users',require('./users'));
router.use('/posts',require('./posts'));
router.use('/comments',require('./comments'));
router.use('/header',require('./header'));
router.use('/likes',require('./likes'));
module.exports=router;