const express=require('express');
const passport=require('passport');
const router=express.Router();
const userController=require('../controllers/user_controller');
router.get('/feeds',passport.checkAuthentication,userController.feeds);
router.post('/create',userController.create);
router.post('/createSession',passport.authenticate('local',{failureRedirect:'/users/signIn'}),userController.createSession);
router.post('/update/:id',passport.checkAuthentication,userController.update);
router.get('/sendRequest/:id',passport.checkAuthentication,userController.sendRequest);
router.get('/addFriend/:id',passport.checkAuthentication,userController.addFriend);
router.get('/removeFriend/:id',passport.checkAuthentication,userController.removeFriend);
router.get('/auth/google', passport.authenticate('google', {scope: ['profile', 'email']}));
router.get('/auth/google/callback', passport.authenticate('google', {failureRedirect: '/users/signIn'}), userController.createSession);
module.exports=router;